/* CVS $Id: $ */
package com.epimorphics.govData.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from ../../../../../resources/ontology/intervals.n3 
 * @author Auto-generated by schemagen on 05 Mar 2010 18:52 
 */
public class INTERVALS {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://reference.data.gov.uk/def/intervals/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The day of the week in which an instant or interval (of duration one day or 
     *  less) occurs.</p>
     */
    public static final Property dayOfWeek = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/dayOfWeek" );
    
    /** <p>hasXsdDurationDescription: a data type property for associating an xsd:duration 
     *  with an Interval. Inspired by "durationDescriptionDataType" mentioned in "http://www.w3.org/TR/owl-time" 
     *  but which seems to have failed to make it into the formal ontology.</p>
     */
    public static final Property hasXsdDurationDescription = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/hasXsdDurationDescription" );
    
    public static final Property intervalContainsDay = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsDay" );
    
    public static final Property intervalContainsDays = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsDays" );
    
    public static final Property intervalContainsHalf = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsHalf" );
    
    public static final Property intervalContainsHalves = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsHalves" );
    
    public static final Property intervalContainsHour = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsHour" );
    
    public static final Property intervalContainsHours = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsHours" );
    
    public static final Property intervalContainsIso8601Week = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsIso8601Week" );
    
    public static final Property intervalContainsMinute = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsMinute" );
    
    public static final Property intervalContainsMinutes = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsMinutes" );
    
    public static final Property intervalContainsMonth = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsMonth" );
    
    public static final Property intervalContainsMonths = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsMonths" );
    
    public static final Property intervalContainsQuarter = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsQuarter" );
    
    public static final Property intervalContainsQuarters = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsQuarters" );
    
    public static final Property intervalContainsSecond = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsSecond" );
    
    public static final Property intervalContainsSeconds = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsSeconds" );
    
    public static final Property intervalContainsWeek = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/intervalContainsWeek" );
    
    /** <p>The month of the year in which a contained instant or interval (of duration 
     *  one month or less) occurs.</p>
     */
    public static final Property monthOfYear = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/monthOfYear" );
    
    /** <p>A reference to the companies house annual reference date at the end of the 
     *  previous reporting year. Annual reporting periods are required to end with 
     *  7 days of this date. Success annual reference dates normally advance by 1 
     *  whole year each year. However, companies can always apply for an earlier reference 
     *  date and under restricted circumstance request a later reference date (upto 
     *  6 months later) see http://www.companieshouse.gov.uk/about/gbhtml/gp2.shtml#ch2</p>
     */
    public static final Property nextAnnualReferenceDate = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/nextAnnualReferenceDate" );
    
    public static final Property nextInterval = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/nextInterval" );
    
    /** <p>The ordinal number of the day of the month in in which an instant or interval 
     *  (of duration less than one day) occurs. The first day of a month has the ordinal 
     *  number 1.</p>
     */
    public static final Property ordinalDayOfMonth = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalDayOfMonth" );
    
    /** <p>The ordinal number of the day of the week in which a (contained) instant or 
     *  interval (of one day or less in duration) occurs. The Monday has an ordinal 
     *  number of 1.</p>
     */
    public static final Property ordinalDayOfWeek = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalDayOfWeek" );
    
    /** <p>The ordinal number of the day of the year in in which an instant or interval 
     *  (of duration one day or less) occurs. The first day of a year has the ordinal 
     *  number 1.</p>
     */
    public static final Property ordinalDayOfYear = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalDayOfYear" );
    
    /** <p>The ordinal number of the half of a year in which a contained instant or interval 
     *  (of duration one half year or less) occurs. The first half of a year has the 
     *  ordinal number 1.</p>
     */
    public static final Property ordinalHalfOfYear = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalHalfOfYear" );
    
    /** <p>The ordinal number of the hour of day in which a (contained) instant or interval 
     *  (of less than one hour duration) occurs. The first hour of a day has ordinal 
     *  number 0.</p>
     */
    public static final Property ordinalHourOfDay = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalHourOfDay" );
    
    /** <p>The ordinal number of the minute of the hour in which a contained instant 
     *  or interval (of duration one hour or less) occurs. The first minute of an 
     *  hour has ordinal number 0.</p>
     */
    public static final Property ordinalMinuteOfHour = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalMinuteOfHour" );
    
    /** <p>The ordinal number of the month of the year in in which an instant or interval 
     *  (of duration one day or less) occurs. The January has the ordinal number 1.</p>
     */
    public static final Property ordinalMonthOfYear = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalMonthOfYear" );
    
    /** <p>The ordinal number of the quarter of the year in which a contained instant 
     *  or interval (of duration one quarter year or less) occurs. The ordinal number 
     *  of the first quarter of a year is 1.</p>
     */
    public static final Property ordinalQuarterOfYear = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalQuarterOfYear" );
    
    /** <p>The ordinal number of the second of the minute in which a contained instant 
     *  or interval (of one second duration or less) occurs. The ordinal number of 
     *  the first second of a minute is 0.</p>
     */
    public static final Property ordinalSecondOfMinute = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalSecondOfMinute" );
    
    /** <p>The ordinal number of the week of the year in which a contained instant or 
     *  interval of one week duration or less occurs. The ordinal number of the first 
     *  week of a year is 1. The first week of a year is the week that contains the 
     *  first Thursday of the year.</p>
     */
    public static final Property ordinalWeekOfYear = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalWeekOfYear" );
    
    /** <p>The ordinal number of the week of year year in which an instant or interval 
     *  (of duration one year or less) occurs. The first year of the AD era has ordinal 
     *  number 1. The Week Of Year is the year to which a week of year pertains, which 
     *  is usually the same as the calendar year except aorund the end of year where 
     *  some days of the week may be deemed to be in the yearr following or the year 
     *  previous depending on the alignment of the year boundary with the weekly cycle.</p>
     */
    public static final Property ordinalWeekOfYearYear = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalWeekOfYearYear" );
    
    /** <p>The ordinal year of the year in which an instant or interval (of duration 
     *  one year or less) occurs. The first year of the AD era has ordinal number 
     *  1.</p>
     */
    public static final Property ordinalYear = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/ordinalYear" );
    
    /** <p>A reference to the companies house annual reference date at the end of the 
     *  previous reporting year. Annual reporting periods are required to end with 
     *  7 days of this date. Success annual reference dates normally advance by 1 
     *  whole year each year. However, companies can always apply for an earlier reference 
     *  date and under restricted circumstance request a later reference date (upto 
     *  6 months later) see http://www.companieshouse.gov.uk/about/gbhtml/gp2.shtml#ch2.</p>
     */
    public static final Property previousAnnualReferenceDate = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/previousAnnualReferenceDate" );
    
    public static final Property previousInterval = m_model.createProperty( "http://reference.data.gov.uk/def/intervals/previousInterval" );
    
    /** <p>A class for business half year intervals. These intervals are not necessarily 
     *  calendar aligned with month boundaries.</p>
     */
    public static final Resource BusinessHalf = m_model.createResource( "http://reference.data.gov.uk/def/intervals/BusinessHalf" );
    
    /** <p>A top-level class for business intervals</p> */
    public static final Resource BusinessInterval = m_model.createResource( "http://reference.data.gov.uk/def/intervals/BusinessInterval" );
    
    public static final Resource BusinessQuarter = m_model.createResource( "http://reference.data.gov.uk/def/intervals/BusinessQuarter" );
    
    /** <p>A class for regular annual business reporting and planning intervals, not 
     *  necessarily calendar aligned.</p>
     */
    public static final Resource BusinessYear = m_model.createResource( "http://reference.data.gov.uk/def/intervals/BusinessYear" );
    
    /** <p>A class for calendar aligned one day intervals, starting at 00:00 (midnight) 
     *  on the relevant day. ISO 8601(E):2004 Section 2.2.6</p>
     */
    public static final Resource CalendarDay = m_model.createResource( "http://reference.data.gov.uk/def/intervals/CalendarDay" );
    
    /** <p>A class for calendar aligned intervals that represent a calendar half year, 
     *  a year being split into two half year periods of 6 months each.</p>
     */
    public static final Resource CalendarHalf = m_model.createResource( "http://reference.data.gov.uk/def/intervals/CalendarHalf" );
    
    /** <p>A class for calendar aligned hour-long intervals. ISO 8601(E):2004 Section 
     *  2.2.4</p>
     */
    public static final Resource CalendarHour = m_model.createResource( "http://reference.data.gov.uk/def/intervals/CalendarHour" );
    
    public static final Resource CalendarInstant = m_model.createResource( "http://reference.data.gov.uk/def/intervals/CalendarInstant" );
    
    /** <p>A class for all calendar aligned intervals. The start of a given interval 
     *  is aligned with the start of each of its first (temporally) subordinate CalendarInterval. 
     *  Halfs are align the start of the first and seventh month of a year; quarters 
     *  with the first, forth, seventh and tenth months; months with calendar months 
     *  sof forth for calendar days, hours,minutes and seconds align</p>
     */
    public static final Resource CalendarInterval = m_model.createResource( "http://reference.data.gov.uk/def/intervals/CalendarInterval" );
    
    /** <p>A class for calendar align one minute intervals. ISO 8601(E):2004 Section 
     *  2.2.3 (for units - 1 minute interval are not defined).</p>
     */
    public static final Resource CalendarMinute = m_model.createResource( "http://reference.data.gov.uk/def/intervals/CalendarMinute" );
    
    /** <p>A class for calendar aligned intervals of one calendar month. ISO 8601(E):2004 
     *  Section 2.2.11</p>
     */
    public static final Resource CalendarMonth = m_model.createResource( "http://reference.data.gov.uk/def/intervals/CalendarMonth" );
    
    /** <p>A class for calendar aligned one-quarter year (3 month) intervals</p> */
    public static final Resource CalendarQuarter = m_model.createResource( "http://reference.data.gov.uk/def/intervals/CalendarQuarter" );
    
    /** <p>A class for calendar aligned one-second intervals. ISO 8601(E):2004 Section 
     *  2.2.1 (and 2.2.2 for leap seconds)(for units - 1 second interval are not defined).</p>
     */
    public static final Resource CalendarSecond = m_model.createResource( "http://reference.data.gov.uk/def/intervals/CalendarSecond" );
    
    /** <p>A class for calendar aligned intervals of one whole year, ie. year long intervals 
     *  that are aligned with the (Gregorian) Calendar. [TODO: how to correctly represent 
     *  the anomaly of the missing 11 days in 1582-10 - possibly need to restrict 
     *  the timeline to being onlt times after the gregorian transition]. ISO 8601(E):2004 
     *  Section 2.2.13</p>
     */
    public static final Resource CalendarYear = m_model.createResource( "http://reference.data.gov.uk/def/intervals/CalendarYear" );
    
    /** <p>A generic superclass for all day like entities.</p> */
    public static final Resource Day = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Day" );
    
    public static final Resource DurationDescriptions = m_model.createResource( "http://reference.data.gov.uk/def/intervals/DurationDescriptions" );
    
    /** <p>A class for intervals that the first half of a (nominally) annual cycle.</p> */
    public static final Resource H1 = m_model.createResource( "http://reference.data.gov.uk/def/intervals/H1" );
    
    /** <p>A class for intervals that the second half of a (nominally) annual cycle.</p> */
    public static final Resource H2 = m_model.createResource( "http://reference.data.gov.uk/def/intervals/H2" );
    
    /** <p>A class for 3rd half year intervals in an abnormally long annual interval 
     *  - in the UK a buisness interval may exceptionally extent to 6 quarters.</p>
     */
    public static final Resource H3 = m_model.createResource( "http://reference.data.gov.uk/def/intervals/H3" );
    
    /** <p>A generic superclass for all half-year (6 month) like intervals</p> */
    public static final Resource Half = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Half" );
    
    /** <p>A generic superclass for hour-long intervals. An hour may contain a positive 
     *  or negative leap second (see http://en.wikipedia.org/wiki/Hour).</p>
     */
    public static final Resource Hour = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Hour" );
    
    public static final Resource Interval = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Interval" );
    
    public static final Resource IntervalList = m_model.createResource( "http://reference.data.gov.uk/def/intervals/IntervalList" );
    
    /** <p>A business interval outside of the normal pattern of business intervals. In 
     *  the UK companies house allow an annual reporting interval to be extended by 
     *  upto 6 months once in 5 years (and at other exceptional times)</p>
     */
    public static final Resource IrregularInterval = m_model.createResource( "http://reference.data.gov.uk/def/intervals/IrregularInterval" );
    
    /** <p>A class for calendar weeks. Strictly not all calendar week intervals are contained 
     *  within the year to which they may be attributed. The first or last week of 
     *  a given calendar year may inculde days from the preceding or following calendar 
     *  year respectively. An ISO 8601 week starts at 00:00:00 in a Monday and ends 
     *  at the last moment of 23:59:59 on the following Sunday. ISO 8601(E):2004 Section 
     *  2.2.8</p>
     */
    public static final Resource Iso8601Week = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Iso8601Week" );
    
    /** <p>A generic superclass for all minute-long intervals. A minute may contain a 
     *  positive or negative leap second.</p>
     */
    public static final Resource Minute = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Minute" );
    
    /** <p>A generic superclass class for all month-long like intervals.</p> */
    public static final Resource Month = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Month" );
    
    /** <p>TODO</p> */
    public static final Resource MonthOfYear = m_model.createResource( "http://reference.data.gov.uk/def/intervals/MonthOfYear" );
    
    /** <p>A class for intervals that are the first quarter of a (nominally) annual cycle.</p> */
    public static final Resource Q1 = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Q1" );
    
    /** <p>A class for intervals that are 2nd quarters of a (nominally) annual cycle</p> */
    public static final Resource Q2 = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Q2" );
    
    /** <p>A class for intervals that are 3rd quarters of a (nominally) annual cycle</p> */
    public static final Resource Q3 = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Q3" );
    
    /** <p>A class for intervals that are 4th quarters of a (nominally) annual cycle.</p> */
    public static final Resource Q4 = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Q4" );
    
    /** <p>A class for 5th quarters of an abnormally long annual interval - in the UK 
     *  a buisness interval may exceptionally extent to 6 quarters.</p>
     */
    public static final Resource Q5 = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Q5" );
    
    /** <p>A class for 6th quarters of an abnormally long annual interval - in the UK 
     *  a buisness interval may exceptionally extent to 6 quarters.</p>
     */
    public static final Resource Q6 = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Q6" );
    
    /** <p>A generic superclass for all Quarter (3-month) long intervals</p> */
    public static final Resource Quarter = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Quarter" );
    
    /** <p>A generic superclass for all one-second long like intervals</p> */
    public static final Resource Second = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Second" );
    
    /** <p>A generic superclass for all one-week long (7 day) intervals.</p> */
    public static final Resource Week = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Week" );
    
    /** <p>A generic superclass for all manner of Year like intervals. The the cardinality 
     *  of days in a year is set to between 351 and 380 because in the UK the end 
     *  of a business reporting year must be within 7 days of an annual reference 
     *  date. In the worst cases this allows a reporting interval to be shortened 
     *  or extended by up to two weeks.</p>
     */
    public static final Resource Year = m_model.createResource( "http://reference.data.gov.uk/def/intervals/Year" );
    
    /** <p>The month of April</p> */
    public static final Resource April = m_model.createResource( "http://reference.data.gov.uk/def/intervals/April" );
    
    /** <p>The month of August</p> */
    public static final Resource August = m_model.createResource( "http://reference.data.gov.uk/def/intervals/August" );
    
    /** <p>The month of December</p> */
    public static final Resource December = m_model.createResource( "http://reference.data.gov.uk/def/intervals/December" );
    
    /** <p>The month of February</p> */
    public static final Resource February = m_model.createResource( "http://reference.data.gov.uk/def/intervals/February" );
    
    /** <p>The month of January</p> */
    public static final Resource January = m_model.createResource( "http://reference.data.gov.uk/def/intervals/January" );
    
    /** <p>The month of July</p> */
    public static final Resource July = m_model.createResource( "http://reference.data.gov.uk/def/intervals/July" );
    
    /** <p>The month of June</p> */
    public static final Resource June = m_model.createResource( "http://reference.data.gov.uk/def/intervals/June" );
    
    /** <p>The month of March</p> */
    public static final Resource March = m_model.createResource( "http://reference.data.gov.uk/def/intervals/March" );
    
    /** <p>The month of May</p> */
    public static final Resource May = m_model.createResource( "http://reference.data.gov.uk/def/intervals/May" );
    
    /** <p>The month of Novermber</p> */
    public static final Resource November = m_model.createResource( "http://reference.data.gov.uk/def/intervals/November" );
    
    /** <p>The month of October</p> */
    public static final Resource October = m_model.createResource( "http://reference.data.gov.uk/def/intervals/October" );
    
    /** <p>The month of September</p> */
    public static final Resource September = m_model.createResource( "http://reference.data.gov.uk/def/intervals/September" );
    
    /** <p>A duration of one day, typically 24 hours)</p> */
    public static final Resource one_day = m_model.createResource( "http://reference.data.gov.uk/def/intervals/one-day" );
    
    /** <p>A duration of one half year, typically 6 months</p> */
    public static final Resource one_half = m_model.createResource( "http://reference.data.gov.uk/def/intervals/one-half" );
    
    /** <p>A duration of one hour</p> */
    public static final Resource one_hour = m_model.createResource( "http://reference.data.gov.uk/def/intervals/one-hour" );
    
    /** <p>A duration of 1 minute</p> */
    public static final Resource one_minute = m_model.createResource( "http://reference.data.gov.uk/def/intervals/one-minute" );
    
    /** <p>A duration of one month</p> */
    public static final Resource one_month = m_model.createResource( "http://reference.data.gov.uk/def/intervals/one-month" );
    
    /** <p>A duration of one quarter, typically 3 months.</p> */
    public static final Resource one_quarter = m_model.createResource( "http://reference.data.gov.uk/def/intervals/one-quarter" );
    
    /** <p>A duration of one second</p> */
    public static final Resource one_second = m_model.createResource( "http://reference.data.gov.uk/def/intervals/one-second" );
    
    /** <p>A duration of one week</p> */
    public static final Resource one_week = m_model.createResource( "http://reference.data.gov.uk/def/intervals/one-week" );
    
    /** <p>A duration of one year</p> */
    public static final Resource one_year = m_model.createResource( "http://reference.data.gov.uk/def/intervals/one-year" );
    
}
